- name: Format code with Prettier
  run: npx prettier --write .
- name: Format code with Prettier
  run: npx prettier --write .

- name: Check formatting with Prettier
  run: npx prettier -c .
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
  with:
    node-version: lts/*
- name: Install dependencies
  run: npm ci
- name: Install Playwright Browsers
  run: npx playwright install --with-deps
- name: Format code with Prettier
  run: npx prettier --write .
- name: Check formatting with Prettier
  run: npx prettier -c .
- name: Run Playwright tests
  run: npx playwright test
- uses: actions/upload-artifact@v4
  if: always()
  with:
    name: playwright-report
    path: playwright-report/
    retention-days: 30
